version: 2

build:
  image: latest
python:
 version: 3.8
 install:
    - requirements: docs/requirements-doc.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
        - test
 system_packages: true
sphinx:
  configuration: docs/source/conf.py
conda:
  environment: docs/environment.yml
